# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: batch.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='batch.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x62\x61tch.proto\"\xbf\x03\n\x05\x42\x61tch\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\"\n\toperators\x18\x03 \x03(\x0b\x32\x0f.Batch.Reporter\x12!\n\tcompanies\x18\x04 \x03(\x0b\x32\x0e.Batch.Company\x12\x0b\n\x03\x65nd\x18\x05 \x01(\x08\x12\x19\n\x04info\x18\x06 \x01(\x0b\x32\x0b.Batch.Info\x12\x11\n\ttimestamp\x18\x07 \x01(\x04\x1a:\n\x08\x44ocument\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0c\n\x04hash\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x1ai\n\x04Info\x12\x0c\n\x04size\x18\x01 \x01(\r\x12\x0e\n\x06weight\x18\x02 \x01(\x02\x12\x0f\n\x07n_items\x18\x03 \x01(\r\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x1d\n\x04\x64ocs\x18\x05 \x03(\x0b\x32\x0f.Batch.Document\x1a\x43\n\x08Reporter\x12\x12\n\npublic_key\x18\x01 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x1a(\n\x07\x43ompany\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\")\n\x0e\x42\x61tchContainer\x12\x17\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x06.Batchb\x06proto3')
)




_BATCH_DOCUMENT = _descriptor.Descriptor(
  name='Document',
  full_name='Batch.Document',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='Batch.Document.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hash', full_name='Batch.Document.hash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='Batch.Document.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=245,
)

_BATCH_INFO = _descriptor.Descriptor(
  name='Info',
  full_name='Batch.Info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='Batch.Info.size', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight', full_name='Batch.Info.weight', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n_items', full_name='Batch.Info.n_items', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='Batch.Info.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='docs', full_name='Batch.Info.docs', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=352,
)

_BATCH_REPORTER = _descriptor.Descriptor(
  name='Reporter',
  full_name='Batch.Reporter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='public_key', full_name='Batch.Reporter.public_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='event_id', full_name='Batch.Reporter.event_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Batch.Reporter.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=421,
)

_BATCH_COMPANY = _descriptor.Descriptor(
  name='Company',
  full_name='Batch.Company',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Batch.Company.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Batch.Company.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=463,
)

_BATCH = _descriptor.Descriptor(
  name='Batch',
  full_name='Batch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Batch.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product_id', full_name='Batch.product_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operators', full_name='Batch.operators', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='companies', full_name='Batch.companies', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='Batch.end', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='info', full_name='Batch.info', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Batch.timestamp', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_BATCH_DOCUMENT, _BATCH_INFO, _BATCH_REPORTER, _BATCH_COMPANY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=463,
)


_BATCHCONTAINER = _descriptor.Descriptor(
  name='BatchContainer',
  full_name='BatchContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='BatchContainer.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=465,
  serialized_end=506,
)

_BATCH_DOCUMENT.containing_type = _BATCH
_BATCH_INFO.fields_by_name['docs'].message_type = _BATCH_DOCUMENT
_BATCH_INFO.containing_type = _BATCH
_BATCH_REPORTER.containing_type = _BATCH
_BATCH_COMPANY.containing_type = _BATCH
_BATCH.fields_by_name['operators'].message_type = _BATCH_REPORTER
_BATCH.fields_by_name['companies'].message_type = _BATCH_COMPANY
_BATCH.fields_by_name['info'].message_type = _BATCH_INFO
_BATCHCONTAINER.fields_by_name['entries'].message_type = _BATCH
DESCRIPTOR.message_types_by_name['Batch'] = _BATCH
DESCRIPTOR.message_types_by_name['BatchContainer'] = _BATCHCONTAINER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Batch = _reflection.GeneratedProtocolMessageType('Batch', (_message.Message,), dict(

  Document = _reflection.GeneratedProtocolMessageType('Document', (_message.Message,), dict(
    DESCRIPTOR = _BATCH_DOCUMENT,
    __module__ = 'batch_pb2'
    # @@protoc_insertion_point(class_scope:Batch.Document)
    ))
  ,

  Info = _reflection.GeneratedProtocolMessageType('Info', (_message.Message,), dict(
    DESCRIPTOR = _BATCH_INFO,
    __module__ = 'batch_pb2'
    # @@protoc_insertion_point(class_scope:Batch.Info)
    ))
  ,

  Reporter = _reflection.GeneratedProtocolMessageType('Reporter', (_message.Message,), dict(
    DESCRIPTOR = _BATCH_REPORTER,
    __module__ = 'batch_pb2'
    # @@protoc_insertion_point(class_scope:Batch.Reporter)
    ))
  ,

  Company = _reflection.GeneratedProtocolMessageType('Company', (_message.Message,), dict(
    DESCRIPTOR = _BATCH_COMPANY,
    __module__ = 'batch_pb2'
    # @@protoc_insertion_point(class_scope:Batch.Company)
    ))
  ,
  DESCRIPTOR = _BATCH,
  __module__ = 'batch_pb2'
  # @@protoc_insertion_point(class_scope:Batch)
  ))
_sym_db.RegisterMessage(Batch)
_sym_db.RegisterMessage(Batch.Document)
_sym_db.RegisterMessage(Batch.Info)
_sym_db.RegisterMessage(Batch.Reporter)
_sym_db.RegisterMessage(Batch.Company)

BatchContainer = _reflection.GeneratedProtocolMessageType('BatchContainer', (_message.Message,), dict(
  DESCRIPTOR = _BATCHCONTAINER,
  __module__ = 'batch_pb2'
  # @@protoc_insertion_point(class_scope:BatchContainer)
  ))
_sym_db.RegisterMessage(BatchContainer)


# @@protoc_insertion_point(module_scope)
