# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: company.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='company.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rcompany.proto\"\xd4\x04\n\x07\x43ompany\x12\x12\n\ncompany_fc\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1b\n\x04info\x18\x03 \x01(\x0b\x32\r.Company.Info\x12\x1c\n\x05roles\x18\x04 \x03(\x0e\x32\r.Company.Role\x12\x0e\n\x06\x61\x64m_pk\x18\x05 \x01(\t\x12$\n\toperators\x18\x06 \x03(\x0b\x32\x11.Company.Reporter\x12\x1e\n\x06\x66ields\x18\x07 \x03(\x0b\x32\x0e.Company.Field\x1a:\n\x08\x44ocument\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0c\n\x04hash\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x1aH\n\x05\x46ield\x12\x10\n\x08id_field\x18\x01 \x01(\t\x12\x0c\n\x04\x61rea\x18\x02 \x01(\r\x12\x1f\n\x04\x64ocs\x18\x03 \x01(\x0b\x32\x11.Company.Document\x1a/\n\x08Location\x12\x10\n\x08latitude\x18\x01 \x01(\t\x12\x11\n\tlongitude\x18\x02 \x01(\t\x1aN\n\x04Info\x12#\n\x08location\x18\x01 \x01(\x0b\x32\x11.Company.Location\x12\x0c\n\x04\x61rea\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x1a\x38\n\x08Reporter\x12\r\n\x05op_pk\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\"U\n\x04Role\x12\x0e\n\nPRODUCTION\x10\x00\x12\x0c\n\x08SUPPLIER\x10\x01\x12\x0e\n\nPROCESSING\x10\x02\x12\x10\n\x0c\x44ISTRIBUTION\x10\x03\x12\r\n\tRETAILING\x10\x04\"-\n\x10\x43ompanyContainer\x12\x19\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x08.Companyb\x06proto3')
)



_COMPANY_ROLE = _descriptor.EnumDescriptor(
  name='Role',
  full_name='Company.Role',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRODUCTION', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUPPLIER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROCESSING', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISTRIBUTION', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RETAILING', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=529,
  serialized_end=614,
)
_sym_db.RegisterEnumDescriptor(_COMPANY_ROLE)


_COMPANY_DOCUMENT = _descriptor.Descriptor(
  name='Document',
  full_name='Company.Document',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='Company.Document.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hash', full_name='Company.Document.hash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='Company.Document.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=266,
)

_COMPANY_FIELD = _descriptor.Descriptor(
  name='Field',
  full_name='Company.Field',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_field', full_name='Company.Field.id_field', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='area', full_name='Company.Field.area', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='docs', full_name='Company.Field.docs', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=340,
)

_COMPANY_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='Company.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='Company.Location.latitude', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Company.Location.longitude', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=389,
)

_COMPANY_INFO = _descriptor.Descriptor(
  name='Info',
  full_name='Company.Info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='Company.Info.location', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='area', full_name='Company.Info.area', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='Company.Info.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=469,
)

_COMPANY_REPORTER = _descriptor.Descriptor(
  name='Reporter',
  full_name='Company.Reporter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='op_pk', full_name='Company.Reporter.op_pk', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='Company.Reporter.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Company.Reporter.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=471,
  serialized_end=527,
)

_COMPANY = _descriptor.Descriptor(
  name='Company',
  full_name='Company',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='company_fc', full_name='Company.company_fc', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='Company.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='info', full_name='Company.info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roles', full_name='Company.roles', index=3,
      number=4, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adm_pk', full_name='Company.adm_pk', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operators', full_name='Company.operators', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fields', full_name='Company.fields', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_COMPANY_DOCUMENT, _COMPANY_FIELD, _COMPANY_LOCATION, _COMPANY_INFO, _COMPANY_REPORTER, ],
  enum_types=[
    _COMPANY_ROLE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=614,
)


_COMPANYCONTAINER = _descriptor.Descriptor(
  name='CompanyContainer',
  full_name='CompanyContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='CompanyContainer.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=616,
  serialized_end=661,
)

_COMPANY_DOCUMENT.containing_type = _COMPANY
_COMPANY_FIELD.fields_by_name['docs'].message_type = _COMPANY_DOCUMENT
_COMPANY_FIELD.containing_type = _COMPANY
_COMPANY_LOCATION.containing_type = _COMPANY
_COMPANY_INFO.fields_by_name['location'].message_type = _COMPANY_LOCATION
_COMPANY_INFO.containing_type = _COMPANY
_COMPANY_REPORTER.containing_type = _COMPANY
_COMPANY.fields_by_name['info'].message_type = _COMPANY_INFO
_COMPANY.fields_by_name['roles'].enum_type = _COMPANY_ROLE
_COMPANY.fields_by_name['operators'].message_type = _COMPANY_REPORTER
_COMPANY.fields_by_name['fields'].message_type = _COMPANY_FIELD
_COMPANY_ROLE.containing_type = _COMPANY
_COMPANYCONTAINER.fields_by_name['entries'].message_type = _COMPANY
DESCRIPTOR.message_types_by_name['Company'] = _COMPANY
DESCRIPTOR.message_types_by_name['CompanyContainer'] = _COMPANYCONTAINER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Company = _reflection.GeneratedProtocolMessageType('Company', (_message.Message,), dict(

  Document = _reflection.GeneratedProtocolMessageType('Document', (_message.Message,), dict(
    DESCRIPTOR = _COMPANY_DOCUMENT,
    __module__ = 'company_pb2'
    # @@protoc_insertion_point(class_scope:Company.Document)
    ))
  ,

  Field = _reflection.GeneratedProtocolMessageType('Field', (_message.Message,), dict(
    DESCRIPTOR = _COMPANY_FIELD,
    __module__ = 'company_pb2'
    # @@protoc_insertion_point(class_scope:Company.Field)
    ))
  ,

  Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), dict(
    DESCRIPTOR = _COMPANY_LOCATION,
    __module__ = 'company_pb2'
    # @@protoc_insertion_point(class_scope:Company.Location)
    ))
  ,

  Info = _reflection.GeneratedProtocolMessageType('Info', (_message.Message,), dict(
    DESCRIPTOR = _COMPANY_INFO,
    __module__ = 'company_pb2'
    # @@protoc_insertion_point(class_scope:Company.Info)
    ))
  ,

  Reporter = _reflection.GeneratedProtocolMessageType('Reporter', (_message.Message,), dict(
    DESCRIPTOR = _COMPANY_REPORTER,
    __module__ = 'company_pb2'
    # @@protoc_insertion_point(class_scope:Company.Reporter)
    ))
  ,
  DESCRIPTOR = _COMPANY,
  __module__ = 'company_pb2'
  # @@protoc_insertion_point(class_scope:Company)
  ))
_sym_db.RegisterMessage(Company)
_sym_db.RegisterMessage(Company.Document)
_sym_db.RegisterMessage(Company.Field)
_sym_db.RegisterMessage(Company.Location)
_sym_db.RegisterMessage(Company.Info)
_sym_db.RegisterMessage(Company.Reporter)

CompanyContainer = _reflection.GeneratedProtocolMessageType('CompanyContainer', (_message.Message,), dict(
  DESCRIPTOR = _COMPANYCONTAINER,
  __module__ = 'company_pb2'
  # @@protoc_insertion_point(class_scope:CompanyContainer)
  ))
_sym_db.RegisterMessage(CompanyContainer)


# @@protoc_insertion_point(module_scope)
