# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='event.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x65vent.proto\"\xd3\x03\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1e\n\x04type\x18\x02 \x01(\x0e\x32\x10.Event.EventType\x12\x1a\n\x05infos\x18\x03 \x01(\x0b\x32\x0b.Event.Info\x12\x10\n\x08reporter\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x04\x12!\n\tharvested\x18\x06 \x01(\x0b\x32\x0e.HarvestedInfo\x12)\n\rtrasformation\x18\x07 \x01(\x0b\x32\x12.TrasformationInfo\x12)\n\rcertification\x18\x08 \x01(\x0b\x32\x12.CertificationInfo\x12\x1d\n\x07generic\x18\t \x01(\x0b\x32\x0c.GenericInfo\x1a:\n\x08\x44ocument\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0c\n\x04hash\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x1a:\n\x04Info\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x1d\n\x04\x64ocs\x18\x02 \x03(\x0b\x32\x0f.Event.Document\"M\n\tEventType\x12\r\n\tHARVESTED\x10\x00\x12\x11\n\rTRASFORMATION\x10\x01\x12\x11\n\rCERTIFICATION\x10\x02\x12\x0b\n\x07GENERIC\x10\x03\"F\n\rHarvestedInfo\x12\x0f\n\x07product\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x02\x12\x12\n\ncompany_cf\x18\x03 \x01(\t\"_\n\x11TrasformationInfo\x12\x13\n\x0bout_product\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61tches\x18\x02 \x03(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x02\x12\x12\n\ncompany_cf\x18\x04 \x01(\t\"\xb0\x01\n\x11\x43\x65rtificationInfo\x12\x32\n\x04type\x18\x01 \x01(\x0e\x32$.CertificationInfo.CertificationType\x12\x12\n\ncompany_cf\x18\x02 \x01(\t\x12\x10\n\x08\x62\x61tch_id\x18\x03 \x01(\t\"A\n\x11\x43\x65rtificationType\x12\x0c\n\x08\x41NALYSIS\x10\x00\x12\r\n\tTREATMENT\x10\x01\x12\x0f\n\x0b\x45NVIRONMENT\x10\x02\"3\n\x0bGenericInfo\x12\x12\n\ncompany_cf\x18\x01 \x01(\t\x12\x10\n\x08\x62\x61tch_id\x18\x02 \x01(\t\")\n\x0e\x45ventContainer\x12\x17\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x06.Eventb\x06proto3')
)



_EVENT_EVENTTYPE = _descriptor.EnumDescriptor(
  name='EventType',
  full_name='Event.EventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HARVESTED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRASFORMATION', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CERTIFICATION', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GENERIC', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=406,
  serialized_end=483,
)
_sym_db.RegisterEnumDescriptor(_EVENT_EVENTTYPE)

_CERTIFICATIONINFO_CERTIFICATIONTYPE = _descriptor.EnumDescriptor(
  name='CertificationType',
  full_name='CertificationInfo.CertificationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ANALYSIS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TREATMENT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENVIRONMENT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=766,
  serialized_end=831,
)
_sym_db.RegisterEnumDescriptor(_CERTIFICATIONINFO_CERTIFICATIONTYPE)


_EVENT_DOCUMENT = _descriptor.Descriptor(
  name='Document',
  full_name='Event.Document',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='Event.Document.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hash', full_name='Event.Document.hash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='Event.Document.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=344,
)

_EVENT_INFO = _descriptor.Descriptor(
  name='Info',
  full_name='Event.Info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='Event.Info.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='docs', full_name='Event.Info.docs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=346,
  serialized_end=404,
)

_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Event.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='Event.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='infos', full_name='Event.infos', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reporter', full_name='Event.reporter', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Event.timestamp', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='harvested', full_name='Event.harvested', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trasformation', full_name='Event.trasformation', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='certification', full_name='Event.certification', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='generic', full_name='Event.generic', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_EVENT_DOCUMENT, _EVENT_INFO, ],
  enum_types=[
    _EVENT_EVENTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=483,
)


_HARVESTEDINFO = _descriptor.Descriptor(
  name='HarvestedInfo',
  full_name='HarvestedInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='product', full_name='HarvestedInfo.product', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='HarvestedInfo.quantity', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='company_cf', full_name='HarvestedInfo.company_cf', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=485,
  serialized_end=555,
)


_TRASFORMATIONINFO = _descriptor.Descriptor(
  name='TrasformationInfo',
  full_name='TrasformationInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='out_product', full_name='TrasformationInfo.out_product', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='batches', full_name='TrasformationInfo.batches', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='TrasformationInfo.quantity', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='company_cf', full_name='TrasformationInfo.company_cf', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=557,
  serialized_end=652,
)


_CERTIFICATIONINFO = _descriptor.Descriptor(
  name='CertificationInfo',
  full_name='CertificationInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='CertificationInfo.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='company_cf', full_name='CertificationInfo.company_cf', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='batch_id', full_name='CertificationInfo.batch_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CERTIFICATIONINFO_CERTIFICATIONTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=655,
  serialized_end=831,
)


_GENERICINFO = _descriptor.Descriptor(
  name='GenericInfo',
  full_name='GenericInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='company_cf', full_name='GenericInfo.company_cf', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='batch_id', full_name='GenericInfo.batch_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=833,
  serialized_end=884,
)


_EVENTCONTAINER = _descriptor.Descriptor(
  name='EventContainer',
  full_name='EventContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='EventContainer.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=886,
  serialized_end=927,
)

_EVENT_DOCUMENT.containing_type = _EVENT
_EVENT_INFO.fields_by_name['docs'].message_type = _EVENT_DOCUMENT
_EVENT_INFO.containing_type = _EVENT
_EVENT.fields_by_name['type'].enum_type = _EVENT_EVENTTYPE
_EVENT.fields_by_name['infos'].message_type = _EVENT_INFO
_EVENT.fields_by_name['harvested'].message_type = _HARVESTEDINFO
_EVENT.fields_by_name['trasformation'].message_type = _TRASFORMATIONINFO
_EVENT.fields_by_name['certification'].message_type = _CERTIFICATIONINFO
_EVENT.fields_by_name['generic'].message_type = _GENERICINFO
_EVENT_EVENTTYPE.containing_type = _EVENT
_CERTIFICATIONINFO.fields_by_name['type'].enum_type = _CERTIFICATIONINFO_CERTIFICATIONTYPE
_CERTIFICATIONINFO_CERTIFICATIONTYPE.containing_type = _CERTIFICATIONINFO
_EVENTCONTAINER.fields_by_name['entries'].message_type = _EVENT
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['HarvestedInfo'] = _HARVESTEDINFO
DESCRIPTOR.message_types_by_name['TrasformationInfo'] = _TRASFORMATIONINFO
DESCRIPTOR.message_types_by_name['CertificationInfo'] = _CERTIFICATIONINFO
DESCRIPTOR.message_types_by_name['GenericInfo'] = _GENERICINFO
DESCRIPTOR.message_types_by_name['EventContainer'] = _EVENTCONTAINER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(

  Document = _reflection.GeneratedProtocolMessageType('Document', (_message.Message,), dict(
    DESCRIPTOR = _EVENT_DOCUMENT,
    __module__ = 'event_pb2'
    # @@protoc_insertion_point(class_scope:Event.Document)
    ))
  ,

  Info = _reflection.GeneratedProtocolMessageType('Info', (_message.Message,), dict(
    DESCRIPTOR = _EVENT_INFO,
    __module__ = 'event_pb2'
    # @@protoc_insertion_point(class_scope:Event.Info)
    ))
  ,
  DESCRIPTOR = _EVENT,
  __module__ = 'event_pb2'
  # @@protoc_insertion_point(class_scope:Event)
  ))
_sym_db.RegisterMessage(Event)
_sym_db.RegisterMessage(Event.Document)
_sym_db.RegisterMessage(Event.Info)

HarvestedInfo = _reflection.GeneratedProtocolMessageType('HarvestedInfo', (_message.Message,), dict(
  DESCRIPTOR = _HARVESTEDINFO,
  __module__ = 'event_pb2'
  # @@protoc_insertion_point(class_scope:HarvestedInfo)
  ))
_sym_db.RegisterMessage(HarvestedInfo)

TrasformationInfo = _reflection.GeneratedProtocolMessageType('TrasformationInfo', (_message.Message,), dict(
  DESCRIPTOR = _TRASFORMATIONINFO,
  __module__ = 'event_pb2'
  # @@protoc_insertion_point(class_scope:TrasformationInfo)
  ))
_sym_db.RegisterMessage(TrasformationInfo)

CertificationInfo = _reflection.GeneratedProtocolMessageType('CertificationInfo', (_message.Message,), dict(
  DESCRIPTOR = _CERTIFICATIONINFO,
  __module__ = 'event_pb2'
  # @@protoc_insertion_point(class_scope:CertificationInfo)
  ))
_sym_db.RegisterMessage(CertificationInfo)

GenericInfo = _reflection.GeneratedProtocolMessageType('GenericInfo', (_message.Message,), dict(
  DESCRIPTOR = _GENERICINFO,
  __module__ = 'event_pb2'
  # @@protoc_insertion_point(class_scope:GenericInfo)
  ))
_sym_db.RegisterMessage(GenericInfo)

EventContainer = _reflection.GeneratedProtocolMessageType('EventContainer', (_message.Message,), dict(
  DESCRIPTOR = _EVENTCONTAINER,
  __module__ = 'event_pb2'
  # @@protoc_insertion_point(class_scope:EventContainer)
  ))
_sym_db.RegisterMessage(EventContainer)


# @@protoc_insertion_point(module_scope)
